name: Unity CICD 😎
on:
  pull_request: {}
  push: { branches: [dev] }
env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_USER }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v2.0-alpha-2
      # Build
      - uses: yukiarrr/unity-build-action@v0.6.1
        with:
          unity-version: 2019.4.17f1
          unity-username: ${{ secrets.UNITY_USER }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_SERIAL }}
          build-target: Android
      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: Output
